name: dotnet CI

on:
  workflow_call:
    inputs:
      enable-test:
        description: Whether to enable tests (1 to enable, 0 to disable)
        default: '1'
        required: false
        type: string
      html-report-format:
        description: Format of HTML report (e.g. Html, HtmlSummary, Cobertura, etc)
        default: Html
        required: false
        type: string
      use-submodules:
        description: Whether to use submodules
        default: false
        required: false
        type: boolean

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    timeout-minutes: 30

    defaults:
      run:
        shell: bash

    steps:
    - name: Setup Git Global Config
      uses: 9506hqwy/actions/common/setup-git-config@main

    - name: Checkout Source Code
      uses: actions/checkout@v6
      with:
        submodules: ${{ inputs.use-submodules }}

    - name: Setup Repository Information
      id: repository
      run: |
        mkdir -p ./artifacts
        echo "name=${GITHUB_REPOSITORY#"${GITHUB_REPOSITORY_OWNER}/"}" >> "${GITHUB_OUTPUT}"

    - name: Restore NuGet Packages Cache
      uses: actions/cache/restore@v5
      with:
        key: ${{ runner.os }}-${{ runner.arch }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        path: |
          ~/.nuget/packages
          !~/.nuget/packages/unwanted
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-nuget-

    - name: Restore Dependencies
      uses: 9506hqwy/actions/dotnet/restore@main

    - name: Build Debug
      uses: 9506hqwy/actions/dotnet/build@main

    - name: Check Format
      uses: 9506hqwy/actions/dotnet/static-analysis@main

    - name: Run Tests
      if: ${{ inputs.enable-test != '0' }}
      uses: 9506hqwy/actions/dotnet/test@main
      with:
        output-dir: artifacts
        html-report-format: ${{ inputs.html-report-format }}

    - name: Build Release
      uses: 9506hqwy/actions/dotnet/build@main
      with:
        configuration: Release

    - name: Generate Artifact
      uses: 9506hqwy/actions/dotnet/artifact@main
      with:
        output-dir: artifacts
        doc-filename: help-${{ steps.repository.outputs.name }}.tar.gz

    - name: Save NuGet Packages Cache
      if: ${{ github.ref_name == 'main' }}
      uses: actions/cache/save@v5
      with:
        key: ${{ runner.os }}-${{ runner.arch }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        path: |
          ~/.nuget/packages
          !~/.nuget/packages/unwanted

    - name: Upload Artifact
      uses: actions/upload-artifact@v5
      with:
        name: ${{ steps.repository.outputs.name }}-${{ github.workflow }}-${{ runner.os }}-${{ runner.arch }}-${{ github.run_number }}
        path: ${{ github.workspace }}/artifacts/
        retention-days: 1
