name: Go CI Ubuntu

on:
  workflow_call:
    inputs:
      enable-lint:
        description: Whether to enable linting (1 to enable, 0 to disable)
        default: '1'
        required: false
        type: string
      use-submodules:
        description: Whether to use submodules
        default: false
        required: false
        type: boolean

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Setup Git Global Config
      uses: 9506hqwy/actions/common/setup-git-config@main

    - name: Checkout Source Code
      uses: actions/checkout@v5
      with:
        submodules: ${{ inputs.use-submodules }}

    - name: Setup
      id: setup
      uses: 9506hqwy/actions/go/setup-bash@main

    - name: Restore Go Modules Cache
      uses: actions/cache/restore@v4
      with:
        key: ${{ runner.os }}-${{ runner.arch }}-go-${{ hashFiles('**/go.sum') }}
        path: |
          ${{ steps.setup.outputs.go-cache }}
          ${{ steps.setup.outputs.go-mod-cache }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-go-

    - name: Check Format
      uses: 9506hqwy/actions/go/static-analysis-bash@main
      with:
        enable-lint: ${{ inputs.enable-lint }}

    - name: Run Tests
      uses: 9506hqwy/actions/go/test-bash@main
      with:
        output-dir: artifacts

    - name: Generate Artifact
      uses: 9506hqwy/actions/go/artifact-bash@main
      with:
        output-dir: artifacts

    - name: Save Go Modules Cache
      if: ${{ github.ref_name == 'main' }}
      uses: actions/cache/save@v4
      with:
        key: ${{ runner.os }}-${{ runner.arch }}-go-${{ hashFiles('**/go.sum') }}
        path: |
          ${{ steps.setup.outputs.go-cache }}
          ${{ steps.setup.outputs.go-mod-cache }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v5
      with:
        name: ${{ steps.setup.outputs.repository-name }}-${{ github.workflow }}-${{ steps.setup.outputs.go-target }}-${{ github.run_number }}
        path: ${{ github.workspace }}/artifacts/
        retention-days: 1
