name: Python CI Ubuntu

on:
  workflow_call:
    inputs:
      use-submodules:
        description: Whether to use submodules
        default: false
        required: false
        type: boolean

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    timeout-minutes: 30

    defaults:
      run:
        shell: bash

    steps:
    - name: Setup Git Global Config
      uses: 9506hqwy/actions/common/setup-git-config@main

    - name: Checkout Source Code
      uses: actions/checkout@v6
      with:
        submodules: ${{ inputs.use-submodules }}

    - name: Restore PyPI Packages Cache
      uses: actions/cache/restore@v5
      with:
        key: ${{ runner.os }}-${{ runner.arch }}-pypi-${{ hashFiles('**/uv.lock') }}
        path: |
          ~/.cache/pip
          ~/.cache/uv
          ~/.local/share/uv
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-pypi-

    - name: Setup
      id: setup
      uses: 9506hqwy/actions/python/setup-bash@main

    - name: Run Tests
      uses: 9506hqwy/actions/python/test-bash@main
      with:
        output-dir: artifacts

    - name: Generate Artifact
      uses: 9506hqwy/actions/python/artifact-bash@main
      with:
        repository-name: ${{ steps.setup.outputs.repository-name }}
        output-dir: artifacts
        doc-filename: help-${{ steps.setup.outputs.repository-name }}.tar.gz

    - name: Reduce UV Cache Size
      run: uv cache prune --ci

    - name: Save PyPI Packages Cache
      if: ${{ github.ref_name == 'main' }}
      uses: actions/cache/save@v5
      with:
        key: ${{ runner.os }}-${{ runner.arch }}-pypi-${{ hashFiles('**/uv.lock') }}
        path: |
          ~/.cache/pip
          ~/.cache/uv
          ~/.local/share/uv

    - name: Upload Artifact
      uses: actions/upload-artifact@v5
      with:
        name: ${{ steps.setup.outputs.repository-name }}-${{ github.workflow }}-${{ runner.os }}-${{ runner.arch }}-${{ github.run_number }}
        path: ${{ github.workspace }}/artifacts/
        retention-days: 1
