name: Rust CI Windows

on:
  workflow_call:
    inputs:
      use-submodules:
        description: Whether to use submodules
        default: false
        required: false
        type: boolean

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    defaults:
      run:
        shell: pwsh

    steps:
    - name: Setup Git Global Config
      uses: 9506hqwy/actions/common/setup-git-config@main

    - name: Checkout Source Code
      uses: actions/checkout@v5
      with:
        submodules: ${{ inputs.use-submodules }}

    - name: Restore Rust Crate Cache
      uses: actions/cache/restore@v4
      with:
        key: ${{ runner.os }}-${{ runner.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        path: |
          ~\.cargo\registry
          ~\.cargo\git
          .\target
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-cargo-

    - name: Setup
      id: setup
      uses: 9506hqwy/actions/rust/setup-pwsh@main

    - name: Run Tests
      uses: 9506hqwy/actions/rust/test-pwsh@main
      with:
        output-dir: artifacts

    - name: Generate Artifact
      uses: 9506hqwy/actions/rust/artifact-pwsh@main
      with:
        output-dir: artifacts
        doc-filename: help-${{ steps.setup.outputs.rust-target }}.zip

    - name: Save Rust Crate Cache
      if: ${{ github.ref_name == 'main' }}
      uses: actions/cache/save@v4
      with:
        key: ${{ runner.os }}-${{ runner.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        path: |
          ~\.cargo\registry
          ~\.cargo\git
          .\target

    - name: Upload Artifact
      uses: actions/upload-artifact@v5
      with:
        name: ${{ steps.setup.outputs.repository-name }}-${{ github.workflow }}-${{ steps.setup.outputs.rust-target }}-${{ github.run_number }}
        path: ${{ github.workspace }}/artifacts/
        retention-days: 1
